### PR TITLE
build and release the app using GitHub Actions

### PR DESCRIPTION
**Pull request by thekyber**
Should solve #52

I believe that my work is complete, this workflow will handle everything from building to signing to creating a relevant tag and release names that are extracted from `app/build.gradle`.

All you need is to launch it when you like to publish a new release.

It is tested and it works pretty well as you can see [here](https://github.com/thekyber/Tubular/actions/runs/8766742131).

You can also check the [release page](https://github.com/thekyber/Tubular/releases) to see the tag and release name, and I also made it to rename the apk file to match yours.

You just have to add `KEYSTORE_BASE64` and `KEYSTORE_PASSWORD` and `GH_TOKEN` with the relevant permissons so it can create the release and upload the files.

### CODE REVIEW

**Comment by polymorphicshade** [comment]
I screwed up something. I'll just apply your changes manually 😁

**Comment by sudoshindo** [comment]
No IzzyOnDroid automation?

**Comment by IzzySoft** [comment]
@sudoshindo which IzzyOnDroid automation do you miss? As long as the APKs are provided at releases, the automation at IzzyOnDroid can take over. Update checker runs daily, thus should fetch updates within < 24h of the APK becoming available at releases – and ship them with the next sync, provided nothing went wrong. I hope this new CI workflow doesn't result in a changed signature, for example, as that would break it and require manual actions (at IzzyOnDroid, but also for everyone having installed the app from there or here).

**Comment by sudoshindo** [comment]
When I saw that the Tubular update was out, I was confused why my F-droid client wasn't showing it. I repeatedly visited the `apt.izzysoft.de` URL to check if the update was out yet.

It was taking a while so I assumed that the Tubular dev had to take some additional action for the update to be published.

**Comment by IzzySoft** [comment]
@sudoshindo the updater for IoD runs once a day, the sync happens around 8 pm local time (6 pm UTC in summer, 7 pm UTC in winter – screw those fiddling with the clock). So when the release happens just after the updater checked, it will be another 24h until it's fetched.

**Comment by sudoshindo** [comment]
Thanks for the explanation. I guess I just need to be more patient.

**Comment by sudoshindo** [comment]
@IzzySoft coming back here seeking clarification.

When you say "local time", you mean Germany time right? And your region doesn't shift their clocks twice per year?

**Comment by IzzySoft** [comment]
> When you say "local time", you mean Germany time right? And your region doesn't shift their clocks twice per year?

I hoped to had that clarified by giving the UTC equivalent:

> around 8 pm local time (6 pm UTC in summer, 7 pm UTC in winter – screw those fiddling with the clock)

So yeah: TZ is Amsterdam, Berlin & Co, and the EU could still not decide which 2019 (that was the date they namend back then, but I've no idea what galactic time zone or reality they mean there) to stop this nonsense with summer/winter time, unfortunately – sorry…

**Pull request closed without merging**
